name: untitled2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  razorpay_flutter: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/dishwashing.jpg
    - assets/bhim.png
    - assets/gpay.jpg
    - assets/paytm.png
    - assets/phonepay.jpg
    - assets/home-cleaning-1.jpg
    - assets/household.jpg
    - assets/intro_background.png
